/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedPlaneacionesRouteImport } from './routes/_authenticated/planeaciones'
import { Route as AuthenticatedProyectosRouteImport } from './routes/_authenticated/proyectos'
import { Route as AuthenticatedSesionesRouteImport } from './routes/_authenticated/sesiones'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlaneacionesRoute =
  AuthenticatedPlaneacionesRouteImport.update({
    id: '/planeaciones',
    path: '/planeaciones',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProyectosRoute = AuthenticatedProyectosRouteImport.update({
  id: '/proyectos',
  path: '/proyectos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSesionesRoute = AuthenticatedSesionesRouteImport.update({
  id: '/sesiones',
  path: '/sesiones',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/planeaciones': typeof AuthenticatedPlaneacionesRoute
  '/proyectos': typeof AuthenticatedProyectosRoute
  '/sesiones': typeof AuthenticatedSesionesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/planeaciones': typeof AuthenticatedPlaneacionesRoute
  '/proyectos': typeof AuthenticatedProyectosRoute
  '/sesiones': typeof AuthenticatedSesionesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/planeaciones': typeof AuthenticatedPlaneacionesRoute
  '/_authenticated/proyectos': typeof AuthenticatedProyectosRoute
  '/_authenticated/sesiones': typeof AuthenticatedSesionesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/auth' | '/dashboard' | '/planeaciones' | '/proyectos' | '/sesiones'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/auth' | '/dashboard' | '/planeaciones' | '/proyectos' | '/sesiones'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/planeaciones'
    | '/_authenticated/proyectos'
    | '/_authenticated/sesiones'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/planeaciones': {
      id: '/_authenticated/planeaciones'
      path: '/planeaciones'
      fullPath: '/planeaciones'
      preLoaderRoute: typeof AuthenticatedPlaneacionesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/proyectos': {
      id: '/_authenticated/proyectos'
      path: '/proyectos'
      fullPath: '/proyectos'
      preLoaderRoute: typeof AuthenticatedProyectosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sesiones': {
      id: '/_authenticated/sesiones'
      path: '/sesiones'
      fullPath: '/sesiones'
      preLoaderRoute: typeof AuthenticatedSesionesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPlaneacionesRoute: typeof AuthenticatedPlaneacionesRoute
  AuthenticatedProyectosRoute: typeof AuthenticatedProyectosRoute
  AuthenticatedSesionesRoute: typeof AuthenticatedSesionesRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPlaneacionesRoute: AuthenticatedPlaneacionesRoute,
  AuthenticatedProyectosRoute: AuthenticatedProyectosRoute,
  AuthenticatedSesionesRoute: AuthenticatedSesionesRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
